const lorem = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum mauris eget maximus facilisis. Integer fermentum, nisl in finibus pharetra, est lacus tristique purus, non tempor ipsum felis ut neque. Vestibulum tempor, orci sit amet tempor mattis, velit quam porttitor justo, a accumsan odio nibh vel sem. Sed dignissim sollicitudin massa eget sollicitudin. Suspendisse suscipit quam quis luctus tristique. Donec viverra finibus purus porta luctus. Integer elementum erat eu consequat aliquet. Sed varius tempor ipsum, ac porttitor arcu mollis vitae. Mauris a libero sapien. Vestibulum a ligula arcu. Etiam placerat congue lorem, quis volutpat urna mollis nec. Curabitur molestie, elit non interdum accumsan, ipsum lorem fringilla nulla, eget varius nunc mauris a turpis.',
  'Pellentesque at sem vestibulum, rutrum tortor ut, placerat sapien. Quisque eget porta odio. Nullam quis blandit est, eu tincidunt tellus. Morbi non vulputate lorem. Donec sit amet tincidunt ipsum, sed lacinia odio. Nullam ac tristique risus, vel ultricies neque. Nunc eu tincidunt libero, volutpat blandit lectus. Praesent viverra leo vitae arcu semper egestas.',
  'Ut elementum risus sit amet nibh sagittis, eget imperdiet orci rutrum. Maecenas bibendum mattis augue eget dictum. Ut id nulla in sapien pharetra finibus id blandit libero. Aliquam dapibus magna nec auctor elementum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam at leo quam. Morbi scelerisque justo quis lacus consectetur faucibus. Donec eget sollicitudin leo. Curabitur nec nulla augue. Fusce consectetur velit libero, a ultrices dui vulputate sit amet. Sed posuere condimentum odio, ut blandit quam fringilla eget. Etiam dignissim feugiat mi eget dignissim. Suspendisse sed nibh sed sapien laoreet pulvinar eu at nulla. Praesent accumsan sem sapien, eu facilisis mi iaculis vitae. Vestibulum nisi nunc, eleifend id neque eu, egestas ultricies magna. Etiam nisl nisi, accumsan sit amet euismod at, sagittis non nibh.',
  'Donec dapibus orci ac lacinia ullamcorper. Sed faucibus condimentum augue, varius laoreet purus aliquet ut. Maecenas non diam est. Aenean non odio vel nisl faucibus ornare et vitae purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in fermentum sem, eget efficitur massa. Nulla eu ante urna. Donec ac rutrum felis. Mauris augue quam, condimentum non ultrices et, gravida a est. Sed in gravida sem.',
  'Nam scelerisque dapibus maximus. Ut ut lorem eget mi placerat dapibus nec a nisi. Etiam condimentum nibh non turpis rhoncus consectetur. Proin vitae accumsan lacus, quis semper est. Nulla convallis tortor vitae odio vehicula, a fringilla augue placerat. Mauris quis lacus a justo faucibus porttitor in at libero. Maecenas aliquet imperdiet risus, eget faucibus arcu porttitor nec. Proin congue euismod arcu quis auctor. Aenean a rhoncus neque, laoreet fermentum massa. Suspendisse vitae nunc urna. Maecenas luctus tincidunt eros, sit amet facilisis lectus fermentum at. Quisque pretium nulla ante, rhoncus cursus enim lacinia malesuada. Vestibulum egestas eros eget libero pellentesque, et dignissim arcu posuere. Cras ultricies felis eget est feugiat, eget vestibulum quam mollis. Nunc interdum, tellus sed ullamcorper malesuada, ex risus vulputate justo, id ornare neque lacus vitae enim.',
].map(e => e.split(' ')).flat();

export default e => lorem.slice(0, e).join(' ');
